language: cpp
os: osx
osx_image: xcode11.3
compiler: gcc

addons:
  homebrew:
    packages:
      - qt
      - open-mesh
      - pugixml
      - bison
      - flex
      - cmake
      - antlr
    update: True

script:
 - cmake . -DCMAKE_INSTALL_PREFIX=$(pwd)/install && make && make install
