name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: checkout submodules
      run: git submodule update --init --recursive
    - name: install ubuntu packages
      run: sudo apt-get update && sudo apt-get install -y qt3d5-dev libpugixml-dev bison flex antlr4 cmake
    - name: configure
      run: mkdir build && cd build && cmake .. -DCMAKE_INSTALL_PREFIX=$(pwd)/../install
    - name: make
      run: make
    - name: make install
      run: make install
